<?php if (!defined('BASEPATH')) exit('No direct script access allowed.');
$dashboard = isset($reception_dashboard) ? $reception_dashboard : array();
$escape = function ($value) { return htmlspecialchars((string) $value, ENT_QUOTES, 'UTF-8'); };
$user = $this->db->get_where('receptionist', array('receptionist_id' => $this->session->userdata('login_user_id')))->row();
$user_name = $user && isset($user->name) ? $user->name : 'Réception';
?>
<div class="reception-dashboard">
    <section class="reception-welcome">
        <div><p class="reception-eyebrow">ESPACE RÉCEPTION</p><h1>Bonjour, <?php echo $escape($user_name); ?>.</h1><p>Accueil, prestations et suivi des patients depuis un seul espace.</p></div>
        <div class="reception-welcome-actions"><a class="btn reception-btn-light" href="<?php echo base_url('receptionist/patient_crud/add'); ?>"><i class="fa fa-user-plus"></i> Nouveau patient</a><a class="btn reception-btn-primary" href="<?php echo base_url('receptionist/invoice_crud/add'); ?>"><i class="fa fa-plus-circle"></i> Nouvelle consultation</a></div>
    </section>
    <section class="reception-stats">
        <a class="reception-stat-card reception-stat-blue" href="<?php echo base_url('receptionist/patient'); ?>"><i class="fa fa-users"></i><span><small>Patients enregistrés</small><strong><?php echo number_format($dashboard['patients_total'] ?? 0, 0, ',', ' '); ?></strong><em>Gérer les dossiers</em></span></a>
        <a class="reception-stat-card reception-stat-violet" href="<?php echo base_url('receptionist/invoice_manage'); ?>"><i class="fa fa-stethoscope"></i><span><small>Consultations</small><strong><?php echo number_format($dashboard['consultations_total'] ?? 0, 0, ',', ' '); ?></strong><em>Voir les reçus</em></span></a>
        <a class="reception-stat-card reception-stat-amber" href="<?php echo base_url('receptionist/examen'); ?>"><i class="fa fa-flask"></i><span><small>Examens</small><strong><?php echo number_format($dashboard['examens_total'] ?? 0, 0, ',', ' '); ?></strong><em>Suivi laboratoire</em></span></a>
        <a class="reception-stat-card reception-stat-green" href="<?php echo base_url('receptionist/appointment_requested'); ?>"><i class="fa fa-calendar-check-o"></i><span><small>Rendez-vous en attente</small><strong><?php echo number_format($dashboard['rendez_vous_attente'] ?? 0, 0, ',', ' '); ?></strong><em>Traiter les demandes</em></span></a>
    </section>
    <section class="reception-quick-actions"><div class="reception-section-heading"><div><p class="reception-eyebrow">ACCÈS RAPIDE</p><h2>Actions fréquentes</h2></div><span><?php echo date('d/m/Y'); ?></span></div><div class="reception-action-grid">
        <a href="<?php echo base_url('receptionist/patient_crud/add'); ?>"><i class="fa fa-user-plus"></i><span>Créer un patient</span></a><a href="<?php echo base_url('receptionist/invoice_crud/add'); ?>"><i class="fa fa-file-text-o"></i><span>Créer une consultation</span></a><a href="<?php echo base_url('receptionist/examen_crud/add'); ?>"><i class="fa fa-flask"></i><span>Ajouter un examen</span></a><a href="<?php echo base_url('receptionist/appointment'); ?>"><i class="fa fa-calendar"></i><span>Rendez-vous</span></a><a href="<?php echo base_url('paiements/historique'); ?>"><i class="fa fa-history"></i><span>Historique paiements</span></a><a href="<?php echo base_url('receptionist/vente'); ?>"><i class="fa fa-shopping-cart"></i><span>Vente pharmacie</span></a>
    </div></section>
    <div class="row reception-dashboard-grids"><div class="col-md-7"><section class="reception-panel"><div class="reception-panel-title"><div><h2>Patients récemment enregistrés</h2><p>Les six derniers dossiers créés.</p></div><a href="<?php echo base_url('receptionist/patient'); ?>">Tout afficher <i class="fa fa-arrow-right"></i></a></div><div class="table-responsive"><table class="table reception-table"><thead><tr><th>Patient</th><th>Téléphone</th><th>Sexe / âge</th><th></th></tr></thead><tbody>
    <?php if (!empty($dashboard['patients_recents'])): foreach ($dashboard['patients_recents'] as $patient): ?><tr><td><strong><?php echo $escape(trim(($patient['name'] ?? '').' '.($patient['prenom'] ?? ''))); ?></strong><small>Dossier #<?php echo (int) $patient['patient_id']; ?></small></td><td><?php echo $escape($patient['phone'] ?? '—'); ?></td><td><?php echo $escape($patient['sex'] ?? '—'); ?><?php echo !empty($patient['age']) ? ' · '.(int) $patient['age'].' ans' : ''; ?></td><td><a class="reception-icon-link" href="<?php echo base_url('receptionist/patient_crud/edit/'.(int) $patient['patient_id']); ?>"><i class="fa fa-arrow-right"></i></a></td></tr><?php endforeach; else: ?><tr><td colspan="4" class="reception-empty">Aucun patient enregistré.</td></tr><?php endif; ?>
    </tbody></table></div></section></div><div class="col-md-5"><section class="reception-panel"><div class="reception-panel-title"><div><h2>Examens à suivre</h2><p>En attente de traitement.</p></div><a href="<?php echo base_url('receptionist/examen'); ?>">Voir tout <i class="fa fa-arrow-right"></i></a></div><div class="reception-list">
    <?php if (!empty($dashboard['examens_attente'])): foreach ($dashboard['examens_attente'] as $exam): ?><a href="<?php echo base_url('receptionist/examen'); ?>"><i class="fa fa-flask"></i><span><strong><?php echo $escape(trim(($exam['name'] ?? '').' '.($exam['prenom'] ?? '')) ?: 'Patient non renseigné'); ?></strong><small>Examen n° <?php echo $escape($exam['examen_number'] ?? $exam['id_examen']); ?></small></span><em>En attente</em></a><?php endforeach; else: ?><div class="reception-empty">Aucun examen en attente.</div><?php endif; ?>
    </div></section></div></div>
    <section class="reception-panel reception-recent-consultations"><div class="reception-panel-title"><div><h2>Dernières consultations</h2><p>Accédez rapidement au reçu ou au dossier concerné.</p></div><a href="<?php echo base_url('receptionist/invoice_manage'); ?>">Toutes les consultations <i class="fa fa-arrow-right"></i></a></div><div class="table-responsive"><table class="table reception-table"><thead><tr><th>Reçu</th><th>Patient</th><th>Date</th><th>Statut</th></tr></thead><tbody>
    <?php if (!empty($dashboard['consultations_recentes'])): foreach ($dashboard['consultations_recentes'] as $invoice): ?><tr><td><strong><?php echo $escape(!empty($invoice['invoice_number']) ? $invoice['invoice_number'] : '#'.$invoice['invoice_id']); ?></strong></td><td><?php echo $escape(trim(($invoice['name'] ?? '').' '.($invoice['prenom'] ?? '')) ?: 'Patient non renseigné'); ?></td><td><?php echo $escape($invoice['creation_datetime'] ?? '—'); ?></td><td><span class="reception-status"><?php echo $escape($invoice['status'] ?? '—'); ?></span></td></tr><?php endforeach; else: ?><tr><td colspan="4" class="reception-empty">Aucune consultation enregistrée.</td></tr><?php endif; ?>
    </tbody></table></div></section>
</div>
