<?php if (!defined('BASEPATH')) exit('No direct script access allowed.'); ?>
<div class="left-sidebar bg-black-300 box-shadow reception-navigation"><div class="sidebar-content"><div class="reception-nav-brand"><span class="reception-nav-mark"><i class="fa fa-heartbeat"></i></span><span><small>ESPACE</small><strong>Réception</strong></span></div><div class="sidebar-nav"><ul class="side-nav color-gray">
    <li class="<?php echo $page_name === 'dashboard' ? 'active' : ''; ?>"><a href="<?php echo base_url('receptionist'); ?>"><i class="fa fa-th-large"></i><span>Tableau de bord</span></a></li>
    <li class="reception-nav-label">ACCUEIL &amp; SOINS</li>
    <li class="<?php echo in_array($page_name, array('manage_patient','add_patient','edit_patient','patient_profile'), true) ? 'active' : ''; ?>"><a href="<?php echo base_url('receptionist/patient'); ?>"><i class="fa fa-users"></i><span>Patients</span></a></li>
    <li class="<?php echo in_array($page_name, array('manage_invoice','add_invoice','edit_invoice','view_invoice'), true) ? 'active' : ''; ?>"><a href="<?php echo base_url('receptionist/invoice_manage'); ?>"><i class="fa fa-stethoscope"></i><span>Consultations</span></a></li>
    <li class="<?php echo in_array($page_name, array('manage_examen','add_examen','edit_examen'), true) ? 'active' : ''; ?>"><a href="<?php echo base_url('receptionist/examen'); ?>"><i class="fa fa-flask"></i><span>Laboratoire</span></a></li>
    <li class="has-children <?php echo in_array($page_name, array('show_appointment','manage_requested_appointment'), true) ? 'open active' : ''; ?>"><a href="#"><i class="fa fa-calendar"></i><span>Rendez-vous</span><i class="fa fa-angle-right arrow"></i></a><ul class="child-nav"><li><a href="<?php echo base_url('receptionist/appointment'); ?>">Agenda</a></li><li><a href="<?php echo base_url('receptionist/appointment_requested'); ?>">Demandes en attente</a></li></ul></li>
    <li class="reception-nav-label">PHARMACIE</li>
    <li class="<?php echo in_array($page_name, array('manage_vente','add_vente','edit_vente'), true) ? 'active' : ''; ?>"><a href="<?php echo base_url('receptionist/vente'); ?>"><i class="fa fa-shopping-cart"></i><span>Ventes</span></a></li>
    <li class="<?php echo in_array($page_name, array('manage_traitement','add_traitement','edit_traitement'), true) ? 'active' : ''; ?>"><a href="<?php echo base_url('receptionist/traitement'); ?>"><i class="fa fa-medkit"></i><span>Traitements</span></a></li>
    <li class="has-children <?php echo in_array($page_name, array('manage_medicine','add_medicine','edit_medicine','manage_stock','add_stock','edit_stock'), true) ? 'open active' : ''; ?>"><a href="#"><i class="fa fa-cubes"></i><span>Stocks &amp; produits</span><i class="fa fa-angle-right arrow"></i></a><ul class="child-nav"><li><a href="<?php echo base_url('receptionist/medicine'); ?>">Médicaments</a></li><li><a href="<?php echo base_url('receptionist/stock'); ?>">Mouvements de stock</a></li></ul></li>
    <li class="reception-nav-label">FINANCES</li>
    <li class="<?php echo $page_name === 'historique_paiement' ? 'active' : ''; ?>"><a href="<?php echo base_url('paiements/historique'); ?>"><i class="fa fa-history"></i><span>Historique paiements</span></a></li>
    <li class="<?php echo in_array($page_name, array('manage_facture','add_facture','edit_facture'), true) ? 'active' : ''; ?>"><a href="<?php echo base_url('receptionist/facture'); ?>"><i class="fa fa-file-text"></i><span>Factures</span></a></li>
    <li class="has-children <?php echo in_array($page_name, array('manage_decaissement','manage_journal_consult','manage_journal_vente'), true) ? 'open active' : ''; ?>"><a href="#"><i class="fa fa-line-chart"></i><span>Journaux</span><i class="fa fa-angle-right arrow"></i></a><ul class="child-nav"><li><a href="<?php echo base_url('receptionist/decaissement'); ?>">Décaissements</a></li><li><a href="<?php echo base_url('receptionist/manage_journal_consult'); ?>">Paiements</a></li><li><a href="<?php echo base_url('receptionist/manage_journal_vente'); ?>">Ventes pharmacie</a></li></ul></li>
    <li class="reception-nav-label">COMPTE</li>
    <li class="<?php echo $page_name === 'edit_profile' ? 'active' : ''; ?>"><a href="<?php echo base_url('receptionist/profile'); ?>"><i class="fa fa-user-circle-o"></i><span>Mon profil</span></a></li>
</ul></div></div></div>
